package org.omg.dds;

/**
 * org/omg/dds/DomainParticipant.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from dds_dcps.idl
 * Monday, August 18, 2008 12:58:40 AM EDT
 */// ----------------------------------------------------------------------
public interface DomainParticipant extends org.omg.dds.Entity {
    org.omg.dds.Publisher create_publisher(org.omg.dds.PublisherListener a_listener);
    org.omg.dds.Subscriber create_subscriber(org.omg.dds.SubscriberListener a_listener);
} // interface DomainParticipant
