package org.omg.dds;


/**
* org/omg/dds/DataReaderListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dds_dcps.idl
* Monday, August 18, 2008 12:58:40 AM EDT
*/

public interface DataReaderListener extends  org.omg.dds.Listener 
{

} // interface DataReaderListener
