package org.omg.dds;

import edu.umb.cs.tinydds.MessagePayload;
import edu.umb.cs.tinydds.OERP.OERP;

/**
 * org/omg/dds/Publisher.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from dds_dcps.idl
 * Monday, August 18, 2008 12:58:40 AM EDT
 */// ----------------------------------------------------------------------
public interface Publisher extends org.omg.dds.Entity {
    org.omg.dds.DataWriter create_datawriter(String a_topic, org.omg.dds.DataWriterListener a_listener);
    int set_listener(org.omg.dds.PublisherListener a_listener);
    org.omg.dds.PublisherListener get_listener();
    //FIXME: should publish here?
    void publish(DataWriter dataWriter, MessagePayload msg);
    void setOERP(OERP oerp);
} // interface Publisher
